# Quarkus Application Configuration
quarkus:
  # Application info
  application:
    name: quarkus-vw
    version: 1.0.0-SNAPSHOT

  # HTTP configuration
  http:
    port: 8080
    host: 0.0.0.0

  # Database configuration
  datasource:
    db-kind: mysql
    username: root
    password: password
    jdbc:
      url: jdbc:mysql://localhost:3306/quarkus_vw_db
      driver: com.mysql.cj.jdbc.Driver
      min-size: 3
      max-size: 13

  # Hibernate ORM configuration
  hibernate-orm:
    database:
      generation: drop-and-create
    log:
      sql: true
    dialect: org.hibernate.dialect.MySQLDialect

  # Development mode configuration
  dev:
    surefire:
      include-tags: "unit"

# Logging configuration
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Profile specific configurations
"%dev":
  quarkus:
    datasource:
      username: root
      password: password
      jdbc:
        url: jdbc:mysql://localhost:3306/quarkus_vw
    hibernate-orm:
      database:
        generation: drop-and-create
      log:
        sql: true

"%test":
  quarkus:
    datasource:
      db-kind: h2
      username: sa
      password: ""
      jdbc:
        url: jdbc:h2:mem:testdb
    hibernate-orm:
      database:
        generation: drop-and-create

"%prod":
  quarkus:
    datasource:
      username: ${DB_USERNAME:root}
      password: ${DB_PASSWORD:password}
      jdbc:
        url: ${DB_URL:jdbc:mysql://localhost:3306/quarkus_vw}
    hibernate-orm:
      database:
        generation: validate
      log:
        sql: false
  logging:
    level:
      root: WARN
